# 使用 StorageClass 表示镜像信息
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: centos-7.4.1708.qcow2
provisioner: driver.extrootfs.io
volumeBindingMode: Immediate
parameters:
  extrootfs.io/type: qcow2
  extrootfs.io/image: "centos-7.4.1708.qcow2"
reclaimPolicy: Delete
allowVolumeExpansion: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 9e848619-171d-488f-917e-2a2fa7f6a896
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: centos-7.4.1708.qcow2
---
apiVersion: v1
kind: Pod
metadata:
  name: centos
spec:
  containers:
    - command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
      image: registry.lqingcloud.cn/library/centos:7.4.1708
      imagePullPolicy: IfNotPresent
      name: centos
      volumeMounts:
      - name: extrootfs
        mountPath: /tmp/extrootfs
  volumes:
  - name: extrootfs
    persistentVolumeClaim:
      claimName: 9e848619-171d-488f-917e-2a2fa7f6a896
      readOnly: true
