apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-driver
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-driver
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Namespace }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io